knp_doctrine_behaviors:
    blameable:      true
    timestampable:  true
    geocodable:     false
    loggable:       false
    sluggable:      false
    soft_deletable: false

sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
        # ...

fos_rest:
    routing_loader:
        default_format: json
    param_fetcher_listener: true
    view:
        view_response_listener: true
        formats:
            xml:  true
            json: true
        templating_formats:
            html: true
    format_listener: true
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    body_listener: true

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: CoreBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"