#imports:
#    - { resource: "@CoreBundle/Resources/config/Doctrine/Apk.orm.yml" }

services:
    admin.apk:
        class: CoreBundle\Admin\ApkAdmin
        arguments: [~, CoreBundle\Entity\Apk, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Apk }

    admin.dht:
        class: CoreBundle\Admin\DhtAdmin
        arguments: [~, CoreBundle\Entity\DhtSensor, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Dht }
