swagger: '2.0'
info:
  title: UnoHouse Android API
  description: Just a test
  version: 0.1.0
host: unohouse.salwa.com.pl
basePath: /v1
schemes:
  - http
paths:
  /app/latest/version:
    get:
      summary: Latest application version
      responses:
        '200':
          description: version of application
  /app/latest/app:
    get:
      summary: Latest application binary file
      responses:
        '200':
          description: binary file
definitions: {}
