sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/admin_security.xml"
sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/admin_resetting.xml"
    prefix: /resetting

core_routes:
    resource: "@CoreBundle/Resources/config/routing.yml"

api_android_routes:
    resource: "@ApiAndroidBundle/Resources/config/routing.yml"
