api_android:
    resource: "@ApiAndroidBundle/Controller/"
    type:     annotation
    prefix:   /api/android

app:
    resource: "@CoreBundle/Controller/"
    type:     annotation

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin