parameters:
    security.acl.permission.map:
        class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap

services:
    sonata.user.admin.group:
        abstract: true
        public: false
